# -*- coding: utf-8 -*-
"""
将 SYSTEM.FNT 转成 C 数组文件 fontlib_bitmap.c, 编译进内部 FLASH.
- 数据源: SD_FILES/SYSTEM.FNT (6763 汉字 x 32 字节 = 216416 字节)
- 顺序: 与 fontlib_unicode_map.h 的 unicode 码点表(升序)一一对应
- 每字 32 字节, 16 行 x 2 字节, 行内 MSB 在前 (LVGL bpp=1 兼容)
"""
import os

ROOT = "f:/stm32探索者ai项目/014_lvgl音乐播放器"
SRC = os.path.join(ROOT, "SD_FILES", "SYSTEM.FNT")
DST = os.path.join(ROOT, "HARDWARE", "FONT", "fontlib_bitmap.c")

with open(SRC, "rb") as f:
    data = f.read()
assert len(data) == 6763 * 32, "unexpected size: %d" % len(data)

lines = [
    "/**",
    " * @file fontlib_bitmap.c",
    " * @brief GB2312 16x16 dot font data, compiled into internal FLASH",
    " *",
    " * 6763 chars x 32 bytes = %d bytes, unicode ascending order," % len(data),
    " * each glyph 32 bytes (16 rows x 2 bytes, MSB first),",
    " * index matches fontlib_unicode_map.h (FONTLIB_CHAR_NUM).",
    " *",
    " * AUTO-GENERATED by tools/gen_fontlib_array.py, do not edit.",
    " */",
    '#include "sys.h"',
    '#include "fontlib_unicode_map.h"',
    "",
    "const u8 fontlib_bitmap_tab[FONTLIB_CHAR_NUM * 32] = {",
]
row = []
for i, b in enumerate(data):
    row.append("0x%02X" % b)
    if len(row) == 16:
        lines.append("    " + ", ".join(row) + ",")
        row = []
if row:
    lines.append("    " + ", ".join(row) + ",")
lines.append("};")

with open(DST, "w", encoding="ascii") as f:
    f.write("\n".join(lines) + "\n")
print("written:", DST)
print("bytes:", len(data), "lines:", len(lines))
