# -*- coding: utf-8 -*-
"""
生成 GB2312 区位码 -> Unicode 查找表 (gbk_unicode_tab.h)
用于把 FATFS 返回的 GBK(_CODE_PAGE=936) 文件名转换成 UTF-8 显示给 LVGL.
- 覆盖 GB2312 区位 1~87 区 (0xA1~0xF7) x 94 位, 共 87*94 = 8178 项
- 有效项存对应 Unicode, 无效项(空位)存 0
- 索引: (hi-0xA1)*94 + (lo-0xA1)
"""
import os

ROOT = "f:/stm32探索者ai项目/014_lvgl音乐播放器"
DST = os.path.join(ROOT, "HARDWARE", "FONT", "gbk_unicode_tab.h")

W = 94
H = 0xF8 - 0xA1  # 0xA1 ~ 0xF7 共 87 区
tab = [0] * (H * W)
cnt = 0
for qh in range(0xA1, 0xF8):
    for ql in range(0xA1, 0xFF):
        try:
            ch = bytes([qh, ql]).decode("gb2312")
            tab[(qh - 0xA1) * W + (ql - 0xA1)] = ord(ch)
            cnt += 1
        except UnicodeDecodeError:
            pass

lines = [
    "/* AUTO-GENERATED by tools/gen_gbk_tab.py, do not edit. */",
    "/* GB2312 quwei code (GBK hi/lo) -> Unicode lookup table. */",
    "/* index = (hi - 0xA1) * 94 + (lo - 0xA1), invalid slot = 0. */",
    "#ifndef __GBK_UNICODE_TAB_H__",
    "#define __GBK_UNICODE_TAB_H__",
    "",
    "#define GBK_TAB_W   94",
    "#define GBK_TAB_H   %d" % H,
    "",
    "static const unsigned short gbk_unicode_tab[GBK_TAB_H * GBK_TAB_W] = {",
]
row = []
for i, u in enumerate(tab):
    row.append("0x%04X" % u)
    if len(row) == 12:
        lines.append("    " + ", ".join(row) + ",")
        row = []
if row:
    lines.append("    " + ", ".join(row) + ",")
lines.append("};")
lines.append("#endif")

with open(DST, "w", encoding="ascii") as f:
    f.write("\n".join(lines) + "\n")
print("written:", DST)
print("chars:", cnt, "table size:", len(tab) * 2, "bytes")
